[package]
name = "nmap-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ipnetwork = "0.21.1"
rand = "0.9.0"
ratatui = "0.29.0"
surge-ping = "0.8.2"
sysinfo = "0.34.2"
tokio = { version = "1.44.2", features = ["full"] }
